# Generated by Django 5.2.7 on 2025-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=10)),
                ('concept', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['date'], name='expenses_tr_date_a834c5_idx'), models.Index(fields=['type', 'date'], name='expenses_tr_type_bfa826_idx')],
            },
        ),
    ]
